# Generated by Django 4.1.7 on 2023-07-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_cartchapter_chapter_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=10),
        ),
    ]
