# Generated by Django 4.1.7 on 2023-07-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_chapter_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Customer')], default=1),
        ),
    ]
